DROP TABLE T1 PURGE;
DROP TABLE T2 PURGE;

CREATE TABLE T1 (C1 NUMBER, C2 VARCHAR2(1));
CREATE TABLE T2 (C1 NUMBER, C3 NUMBER);

SELECT A.C1, B.C3
  FROM T1 A CROSS JOIN T2 B;

SELECT A.C1, B.C3
  FROM T1 A INNER JOIN T2 B
    ON B.C1 = A.C1;

SELECT A.C1, B.C3
  FROM T1 A NATURAL JOIN T2 B;

SELECT C1, C3
  FROM T1 A LEFT OUTER JOIN T2 B
 USING (C1);
