DROP TABLE T1;

CREATE TABLE T1 (C1 VARCHAR2(10));

INSERT INTO T1 (C1) VALUES ('ABC');
INSERT INTO T1 (C1) VALUES ('LVXYZ');
INSERT INTO T1 (C1) VALUES ('HNMK');

COMMIT;

SELECT SUBSTR (C1, LENGTH (C1) - 1, 1) AS R1 FROM T1;
