DROP TABLE T1 PURGE;
DROP TABLE T2 PURGE;

CREATE TABLE T1 (C1 NUMBER, C2 VARCHAR2(1));
CREATE TABLE T2 (C1 NUMBER, C2 NUMBER);

INSERT INTO T1 (C1, C2) VALUES (1, 'A');
INSERT INTO T1 (C1, C2) VALUES (2, 'B');
INSERT INTO T1 (C1, C2) VALUES (3, 'C');
INSERT INTO T1 (C1, C2) VALUES (4, 'D');

INSERT INTO T2 (C1, C2) VALUES (1, 1);
INSERT INTO T2 (C1, C2) VALUES (2, 1);
INSERT INTO T2 (C1, C2) VALUES (2, 2);
INSERT INTO T2 (C1, C2) VALUES (2, 3);
INSERT INTO T2 (C1, C2) VALUES (4, 1);
INSERT INTO T2 (C1, C2) VALUES (4, 2);

COMMIT;

SELECT *
  FROM T1 A, T2 B
 WHERE A.C2 IN ('B', 'C')
   AND B.C1(+) = A.C1
   AND B.C2 <= 2;

SELECT *
  FROM T1 A INNER JOIN T2 B
    ON B.C1 = A.C1
 WHERE A.C2 IN ('B', 'C')
   AND B.C2 <= 2;

SELECT *
  FROM T1 A LEFT OUTER JOIN T2 B
    ON B.C1 = A.C1
   AND B.C2 <= 2
 WHERE A.C2 IN ('B', 'C');

SELECT *
  FROM T1 A RIGHT OUTER JOIN T2 B
    ON B.C1 = A.C1
   AND A.C2 IN ('B', 'C')
 WHERE B.C2 <= 2;

SELECT *
  FROM T1 A CROSS JOIN T2 B
 WHERE A.C2 IN ('B', 'C')
   AND B.C2 <= 2;
