DROP TABLE T1 PURGE;
DROP TABLE T2 PURGE;

CREATE TABLE T1 (C1 VARCHAR2(1), C2 NUMBER);
CREATE TABLE T2 (C1 VARCHAR2(1), C2 NUMBER);

SELECT C1, C2 FROM T1
UNION ALL
SELECT C1 FROM T2;

SELECT C1, C2 FROM T1
UNION ALL
SELECT C2, C1 FROM T2;

SELECT C1, C2 FROM T1 ORDER BY C1
UNION ALL
SELECT C1, C2 FROM T2 ORDER BY C1;

(SELECT C1, C2 FROM T1)
UNION ALL
(SELECT C1, C2 FROM T2);
