DROP TABLE T1 PURGE;

CREATE TABLE T1 (C1 NUMBER NOT NULL, C2 NUMBER NOT NULL);

INSERT INTO T1 VALUES (1, 1);
INSERT INTO T1 VALUES (1, 2);
INSERT INTO T1 VALUES (2, 1);
INSERT INTO T1 VALUES (2, 2);
INSERT INTO T1 VALUES (3, 1);
INSERT INTO T1 VALUES (3, 2);
INSERT INTO T1 VALUES (4, 1);
INSERT INTO T1 VALUES (4, 2);

COMMIT;

SELECT * FROM T1 WHERE (C1 = 3 OR C2 = 1)
ORDER BY 1, 2;

SELECT * FROM T1 WHERE C1 = 3
UNION ALL
SELECT * FROM T1 WHERE C2 = 1 AND C1 <> 3
ORDER BY 1, 2;