SELECT *
  FROM (SELECT A.EMPNO, A.ENAME, A.SAL, A.DEPTNO, B.DNAME
          FROM EMP A
             , DEPT B
         WHERE B.DEPTNO(+) = A.DEPTNO
        ORDER BY SAL DESC)
 WHERE ROWNUM <= 3;

SELECT A.*
     , B.DNAME
  FROM (SELECT EMPNO, ENAME, SAL, DEPTNO
          FROM EMP
         ORDER BY SAL DESC) A
     , DEPT B
 WHERE ROWNUM <= 3
   AND B.DEPTNO(+) = A.DEPTNO;
