SELECT EMPNO, ENAME, SAL, DEPTNO
  FROM EMP
 ORDER BY SAL DESC;

SELECT A.*, ROWNUM AS RN
  FROM (SELECT EMPNO, ENAME, SAL, DEPTNO
          FROM EMP
         ORDER BY SAL DESC) A
 WHERE ROWNUM <= 10;

SELECT A.*
  FROM (SELECT A.*
             , ROWNUM AS RN
          FROM (SELECT EMPNO, ENAME, SAL, DEPTNO
                  FROM EMP
                 ORDER BY SAL DESC) A
         WHERE ROWNUM <= 10) A
 WHERE RN >= 6;
