DROP TABLE T1 PURGE;

CREATE TABLE T1 (C1 NUMBER, C2 NUMBER);

INSERT INTO T1 (C1, C2) VALUES (1, NULL);

COMMIT;

SELECT NVL (C2, 0) AS R1 FROM T1;

SELECT NULLIF (C1, 1) AS R1 FROM T1;

SELECT DECODE (C1, 1, 0) AS R1 FROM T1;

SELECT COALESCE (C2, NULL, 0) AS R1 FROM T1;
