DROP TABLE T1 PURGE;

CREATE TABLE T1 (C1 NUMBER);

INSERT INTO T1 (C1) VALUES (1);
INSERT INTO T1 (C1) VALUES (2);
INSERT INTO T1 (C1) VALUES (NULL);
INSERT INTO T1 (C1) VALUES (3);
INSERT INTO T1 (C1) VALUES (NULL);

COMMIT;

SELECT COUNT (*) AS R1 FROM T1 WHERE C1 IN (1, 2, NULL);
