SELECT EMPNO, ENAME, DEPTNO, SAL
  FROM EMP
 WHERE DEPTNO IN (10, 20)
 ORDER BY 3 DESC, 4, 1;

SELECT EMPNO, ENAME, DEPTNO, SAL
  FROM EMP
 WHERE DEPTNO = 10
 UNION ALL
SELECT EMPNO, ENAME, DEPTNO, SAL
  FROM EMP
 WHERE DEPTNO = 20
 ORDER BY 3 DESC, 4, 1;

SELECT EMPNO, ENAME, DEPTNO, SAL
  FROM (SELECT EMPNO, ENAME, DEPTNO, SAL
          FROM EMP
         WHERE DEPTNO = 10
         ORDER BY 3 DESC, 4, 1)
 UNION ALL
SELECT EMPNO, ENAME, DEPTNO, SAL
  FROM (SELECT EMPNO, ENAME, DEPTNO, SAL
          FROM EMP
         WHERE DEPTNO = 20
         ORDER BY 3 DESC, 4, 1);

SELECT EMPNO, ENAME, DEPTNO, SAL
  FROM (SELECT EMPNO, ENAME, DEPTNO, SAL
          FROM EMP
         WHERE DEPTNO IN (10, 20))
 ORDER BY DEPTNO DESC, SAL, EMPNO;
