SELECT *
  FROM DEPT
 WHERE DEPTNO IN (SELECT DEPTNO FROM EMP);

SELECT *
  FROM DEPT
 WHERE DEPTNO = ALL (SELECT DEPTNO FROM EMP);

SELECT A.*
  FROM DEPT A
 WHERE EXISTS (SELECT 1
                 FROM EMP X
                WHERE X.DEPTNO = A.DEPTNO);

SELECT A.*
  FROM DEPT A
 WHERE (SELECT COUNT (*)
          FROM EMP X
         WHERE X.DEPTNO = A.DEPTNO) > 1;
