DROP TABLE T1 PURGE;

CREATE TABLE T1 (C1 NUMBER, C2 NUMBER);

INSERT INTO T1 VALUES (1, 1);
INSERT INTO T1 VALUES (1, 2);
INSERT INTO T1 VALUES (2, 1);
INSERT INTO T1 VALUES (2, 2);

COMMIT;

SELECT 1 AS TP, C1, C2 FROM T1 WHERE C1 = 1
UNION ALL
SELECT 2 AS TP, C1, C2 FROM T1 WHERE C2 = 1;
