SELECT EMPNO, ENAME, JOB, SAL
     , LAST_VALUE (SAL) OVER (PARTITION BY JOB ORDER BY SAL
           RANGE BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) AS C1
     , LAST_VALUE (SAL) OVER (PARTITION BY JOB ORDER BY SAL) AS C2
  FROM EMP
 WHERE DEPTNO = 20;
