SELECT *
  FROM DEPT A
 WHERE EXISTS (SELECT 1 FROM EMP X WHERE X.DEPTNO = A.DEPTNO AND ROWNUM = 1);

SELECT A.EMPNO, A.ENAME
     , NVL ((SELECT 'Y' FROM EMP X WHERE X.DEPTNO = A.DEPTNO AND ROWNUM = 1), 'N') AS YN
  FROM EMP A;

SELECT *
   FROM DEPT
  WHERE DEPTNO IN (SELECT DEPTNO
                     FROM (SELECT DEPTNO, AVG(SAL) AS SAL
                             FROM EMP
                            GROUP BY DEPTNO
                            ORDER BY SAL DESC)
                    WHERE ROWNUM <= 1);

SELECT *
  FROM (SELECT * FROM EMP ORDER BY SAL DESC)
 WHERE ROWNUM <= 1;
