 SELECT EMPNO, ENAME, MGR, SYS_CONNECT_BY_PATH (ENAME, '>') AS PATH
   FROM EMP
  START WITH ENAME = 'SCOTT'
CONNECT BY EMPNO = PRIOR MGR;

 SELECT SUBSTR (MAX (SYS_CONNECT_BY_PATH (ENAME, '>')), 2) AS PATH
   FROM EMP
  START WITH ENAME = 'SCOTT'
CONNECT BY EMPNO = PRIOR MGR;

 SELECT LISTAGG (ENAME, '>') WITHIN GROUP (ORDER BY LEVEL DESC) AS PATH
   FROM EMP
  START WITH ENAME = 'SCOTT'
CONNECT BY EMPNO = PRIOR MGR;
