DROP TABLE T1 PURGE;
DROP TABLE T2 PURGE;
DROP TABLE T3 PURGE;
DROP TABLE T4 PURGE;

CREATE TABLE T1 (C1 NUMBER);
CREATE TABLE T2 (C1 NUMBER);
CREATE TABLE T3 (C1 NUMBER);
CREATE TABLE T4 (C1 NUMBER);

INSERT INTO T4 VALUES (1);
INSERT INTO T4 VALUES (2);
INSERT INTO T4 VALUES (3);

COMMIT;

INSERT FIRST
  WHEN C1 >= 2 THEN INTO T1
  WHEN C1 >= 3 THEN INTO T2
  ELSE INTO T3
SELECT C1 FROM T4;

SELECT COUNT (*) AS CNT FROM T1;
SELECT COUNT (*) AS CNT FROM T2;
SELECT COUNT (*) AS CNT FROM T3;
