DROP TABLE T1 PURGE;

CREATE TABLE T1 (C1 NUMBER NOT NULL, C2 NUMBER);

INSERT INTO T1 VALUES (1, 1);
INSERT INTO T1 VALUES (2, 2);

COMMIT;

VAR V1 NUMBER;
EXEC :V1 := 1;

SELECT * FROM T1 WHERE C1 = NVL (:V1, C1);

SELECT * FROM T1 WHERE :V1 IS NULL
UNION ALL
SELECT * FROM T1 WHERE :V1 IS NOT NULL AND C1 = :V1;
