-- SYS
DROP USER U1 CASCADE;
DROP USER U2 CASCADE;

CREATE USER U1 IDENTIFIED BY U1;
CREATE USER U2 IDENTIFIED BY U2;

GRANT CREATE SESSION TO U1, U2;

-- U1
GRANT CREATE ANY TABLE TO U2;

-- SYS
GRANT CREATE ANY TABLE TO U1 WITH ADMIN OPTION;

-- U1
GRANT CREATE ANY TABLE TO U2;
