SELECT CONCAT ('DB', 'ian') AS R1 FROM DUAL;

SELECT SUBSTR ('DBian Corp.', 1, 5) AS R1 FROM DUAL;

SELECT 'DB' || UPPER ('iAN') AS R1 FROM DUAL;

SELECT REPLACE ('DBian Corp.', ' Corp.') AS R1 FROM DUAL;
