DROP TABLE T1 PURGE;

CREATE TABLE T1 (C1 VARCHAR2(1));

INSERT INTO T1 (C1) VALUES ('A');
INSERT INTO T1 (C1) VALUES (NULL);
INSERT INTO T1 (C1) VALUES (NULL);
INSERT INTO T1 (C1) VALUES ('B');
INSERT INTO T1 (C1) VALUES (NULL);

COMMIT;

SELECT C1 FROM T1 WHERE C1 = NULL;
SELECT C1 FROM T1 WHERE C1 = '';
SELECT C1 FROM T1 WHERE C1 IS NULL;
SELECT C1 FROM T1 WHERE C1 IN (NULL, '');
