DROP TABLE T1 PURGE;

CREATE TABLE T1 (C1 VARCHAR2(10));

INSERT INTO T1 (C1) VALUES ('ABCD');
INSERT INTO T1 (C1) VALUES ('A_C%');
INSERT INTO T1 (C1) VALUES ('ABC');
INSERT INTO T1 (C1) VALUES ('ABBCD');

COMMIT;

SELECT SUM (LENGTH (C1)) AS R1 FROM T1 WHERE C1 LIKE 'A_C%';
