DROP TABLE T1 PURGE;

CREATE TABLE T1 (C1 NUMBER(2, 1));

INSERT INTO T1 (C1) VALUES (3.5);
INSERT INTO T1 (C1) VALUES (4.0);
INSERT INTO T1 (C1) VALUES (5.5);
INSERT INTO T1 (C1) VALUES (6.0);

COMMIT;

SELECT SUM (ROUND (C1))     AS R1 FROM T1;

SELECT ROUND (SUM (C1))     AS R1 FROM T1;

SELECT SUM (CEIL (C1))      AS R1 FROM T1;

SELECT ROUND (SUM (C1), -1) AS R1 FROM T1;
