SELECT JOB, COUNT (*) AS CNT
  FROM EMP
 GROUP BY JOB;

SELECT DEPTNO, SUM (SAL) AS SAL
  FROM EMP
 GROUP BY DEPTNO, JOB;

SELECT TO_CHAR (HIREDATE, 'YYYY') AS HIREYEAR, COUNT (*) AS CNT
  FROM EMP
 GROUP BY HIREDATE;

SELECT HIREDATE, SUM (SAL) AS SAL
  FROM EMP
 GROUP BY TO_CHAR (HIREDATE, 'YYYY-MM-DD');
