DROP TABLE T1 PURGE;

CREATE TABLE T1 (C1 NUMBER, C2 VARCHAR2(4));

INSERT INTO T1 (C1, C2) VALUES (1, 'ZA');
INSERT INTO T1 (C1, C2) VALUES (2, 'BZZ');
INSERT INTO T1 (C1, C2) VALUES (3, 'CZZ');
INSERT INTO T1 (C1, C2) VALUES (4, 'DZZZ');
INSERT INTO T1 (C1, C2) VALUES (5, 'ZZZE');

COMMIT;

SELECT C1, C2
  FROM T1
 ORDER BY CASE
              WHEN C1 <= 2 THEN 'B'
              WHEN C1 >  4 THEN 'A'
              ELSE 'C'
           END
         , RTRIM (C2, 'Z');
