DROP TABLE T1;
DROP TABLE T2;

CREATE TABLE T1 (C1 NUMBER, C2 VARCHAR2(1));
CREATE TABLE T2 (C1 NUMBER, C2 VARCHAR2(1));

INSERT INTO T1 (C1, C2) VALUES (1, 'A');
INSERT INTO T1 (C1, C2) VALUES (2, 'B');
INSERT INTO T1 (C1, C2) VALUES (3, 'C');

INSERT INTO T2 (C1, C2) VALUES (1, 'A');
INSERT INTO T2 (C1, C2) VALUES (1, 'B');
INSERT INTO T2 (C1, C2) VALUES (2, 'B');
INSERT INTO T2 (C1, C2) VALUES (3, 'B');
INSERT INTO T2 (C1, C2) VALUES (3, 'C');

COMMIT;

SELECT SUM (B.C1) AS R1
  FROM T1 A, T2 B
 WHERE B.C2 > A.C2;
