DROP TABLE T1 PURGE;
DROP TABLE T2 PURGE;

CREATE TABLE T1 (C1 NUMBER);
CREATE TABLE T2 (C1 NUMBER);

INSERT INTO T1 VALUES (1);
INSERT INTO T1 VALUES (2);
INSERT INTO T1 VALUES (3);

INSERT INTO T2 VALUES (1);
INSERT INTO T2 VALUES (2);

COMMIT;

SELECT   A.DEPTNO, B.DNAME
       , SUM (A.SAL) AS SAL
    FROM EMP A
       , DEPT B
   WHERE B.DEPTNO = A.DEPTNO
GROUP BY A.DEPTNO, B.DNAME;

SELECT A.DEPTNO, B.DNAME, A.SAL
  FROM (SELECT DEPTNO
             , SUM (SAL) AS SAL
          FROM EMP
         GROUP BY DEPTNO) A
     , DEPT B
 WHERE B.DEPTNO = A.DEPTNO;
