SELECT EMPNO, ENAME, JOB, SAL
     , MAX (SAL) OVER () - MIN (SAL) OVER (PARTITION BY JOB) AS C1
     , MAX (SAL) OVER () AS C2
     , MIN (SAL) OVER (PARTITION BY JOB) AS C3
  FROM EMP
 WHERE DEPTNO = 20;
