SELECT A.*
  FROM (SELECT EMPNO, ENAME, SAL, ROWNUM AS RN
          FROM EMP
         ORDER BY SAL DESC) A
 WHERE RN BETWEEN 6 AND 10;

SELECT A.*, ROWNUM AS RN
  FROM (SELECT EMPNO, ENAME, SAL
          FROM EMP
         ORDER BY SAL DESC) A
 WHERE ROWNUM BETWEEN 6 AND 10;

SELECT *
  FROM (SELECT A.*, ROWNUM AS RN
          FROM (SELECT EMPNO, ENAME, SAL
                  FROM EMP
                 ORDER BY SAL DESC) A)
 WHERE RN BETWEEN 6 AND 10;

SELECT *
  FROM (SELECT A.*, ROWNUM AS RN
          FROM (SELECT EMPNO, ENAME, SAL
                  FROM EMP
                  ORDER BY SAL DESC) A
         WHERE ROWNUM <= 10)
 WHERE RN >= 6;
