SELECT A.*
  FROM (SELECT A.*, ROWNUM AS RN
          FROM (SELECT EMPNO, ENAME, SAL
                  FROM EMP
                 ORDER BY SAL DESC) A
         WHERE ROWNUM <= 10) A
 WHERE A.RN >= 6;

SELECT EMPNO, ENAME, SAL
  FROM EMP
 ORDER BY SAL DESC OFFSET 5 ROWS FETCH NEXT 5 ROWS ONLY;
