 SELECT EMPNO, ENAME, MGR, CONNECT_BY_ISLEAF AS ISLEAF
   FROM EMP
  -- WHERE CONNECT_BY_ISLEAF = 1
  START WITH ENAME = 'JONES'
CONNECT BY MGR = PRIOR EMPNO;

 SELECT COUNT (*) AS CNT
   FROM EMP
  WHERE CONNECT_BY_ISLEAF = 1
  START WITH ENAME = 'JONES'
CONNECT BY MGR = PRIOR EMPNO;
