DROP TABLE T1 PURGE;
DROP TABLE T2 PURGE;

CREATE TABLE T1 (C1 NUMBER, C2 NUMBER);
CREATE TABLE T2 (C1 NUMBER, C2 NUMBER);

INSERT INTO T1 VALUES (1, 1);
INSERT INTO T2 VALUES (1, 2);

COMMIT;

UPDATE (SELECT A.C2 AS AC2, B.C2 AS BC2
          FROM T1 A, T2 B
         WHERE B.C1 = A.C1)
   SET AC2 = BC2;
