DROP TABLE T1 PURGE;

CREATE TABLE T1 (C1 NUMBER);

INSERT INTO T1 VALUES (1);
SAVEPOINT P1;
INSERT INTO T1 VALUES (2);
SAVEPOINT P2;
INSERT INTO T1 VALUES (3);
SAVEPOINT P3;
INSERT INTO T1 VALUES (4);
SAVEPOINT P4;

ROLLBACK TO SAVEPOINT P1;
ROLLBACK TO SAVEPOINT P3;

SELECT COUNT (*) AS CNT FROM T1;
