DROP TABLE T1 PURGE;

CREATE TABLE T1 (C1 VARCHAR2(2));

INSERT INTO T1 VALUES ('A');

COMMIT;

ALTER TABLE T1 MODIFY C1 VARCHAR2(1);
ALTER TABLE T1 MODIFY C1 VARCHAR2(3);
ALTER TABLE T1 MODIFY C1 NULL;
ALTER TABLE T1 MODIFY C1 NOT NULL;
