DROP TABLE T1 PURGE;
CREATE TABLE T1 (C1 VARCHAR2(1 BYTE), C2 VARCHAR2(1 CHAR));

INSERT INTO T1 (C1) VALUES ('A' );
INSERT INTO T1 (C2) VALUES ('A' );
INSERT INTO T1 (C1) VALUES ('°¡');
INSERT INTO T1 (C2) VALUES ('°¡');
