DROP TABLE T1 PURGE;

CREATE TABLE T1 (C1 NUMBER, C2 NUMBER);

INSERT INTO T1 VALUES (1, 1);
INSERT INTO T1 VALUES (2, 2);

COMMIT;

SELECT *
  FROM T1
 WHERE (   (:V1 = 1 AND C1 = :V2)
        OR (:V1 = 2 AND C2 = :V2));

SELECT * FROM T1 WHERE :V1 = 1 AND C1 = :V2
UNION ALL
SELECT * FROM T1 WHERE :V1 = 2 AND C2 = :V2;
