-- SYS
DROP USER U1 CASCADE;
DROP USER U2 CASCADE;
DROP USER U3 CASCADE;

CREATE USER U1 IDENTIFIED BY U1;
CREATE USER U2 IDENTIFIED BY U2;
CREATE USER U3 IDENTIFIED BY U3;

GRANT CREATE SESSION TO U1, U2, U3;

-- U2
CREATE TABLE T1 (C1 NUMBER);

GRANT ALL ON T1 TO U1;

-- U1
GRANT ALTER ON U2.T1 TO U3;

-- U2
GRANT ALTER ON T1 TO U1 WITH GRANT OPTION;

-- U1
GRANT ALTER ON U2.T1 TO U3;
