SELECT LTRIM ('XXABXC', 'XX') AS R1 FROM DUAL;

SELECT RTRIM ('ABXCX', 'X') AS R1 FROM DUAL;

SELECT TRIM ('X' FROM 'XXABXCX') AS R1 FROM DUAL;

SELECT TRIM (TRAILING 'X' FROM 'XXABXC') AS R1 FROM DUAL;
