DROP TABLE COMMISSION PURGE;

CREATE TABLE COMMISSION (EMPNO NUMBER(4), COMM NUMBER);

INSERT INTO COMMISSION (EMPNO, COMM) VALUES (1, 1000);
INSERT INTO COMMISSION (EMPNO, COMM) VALUES (2, NULL);
INSERT INTO COMMISSION (EMPNO, COMM) VALUES (3, 2000);

COMMIT;

SELECT NVL (TO_CHAR (COMM), '없음') AS R1 FROM COMMISSION;

SELECT NVL (TO_NUMBER (COMM), '없음') AS R1 FROM COMMISSION;

SELECT NVL (ABS (COMM), '없음') AS R1 FROM COMMISSION;

SELECT NVL (LENGTH (COMM), '없음') AS R1 FROM COMMISSION;
