SELECT *
  FROM EMP
 WHERE JOB IN ('CLERK', 'MANAGER')
   AND DEPTNO = 20
   AND SAL BETWEEN 1000 AND 3000;

SELECT *
  FROM EMP
 WHERE JOB = 'CLERK'
    OR JOB = 'MANAGER'
   AND DEPTNO = 20
   AND SAL BETWEEN 1000 AND 3000;

SELECT *
  FROM EMP
 WHERE JOB IN ('CLERK')
    OR JOB IN ('MANAGER')
   AND DEPTNO = 20
   AND SAL >= 1000
   AND SAL <= 3000;

SELECT *
  FROM EMP
 WHERE (   JOB = 'CLERK'
        OR JOB = 'MANAGER')
   AND DEPTNO = 20
   AND SAL BETWEEN 1000 AND 3000;

SELECT *
  FROM EMP
 WHERE JOB = 'CLERK'
    OR JOB = 'MANAGER'
   AND DEPTNO = 20
   AND (    SAL >= 1000
        AND SAL <= 3000);
