SELECT *
  FROM EMP
 WHERE NOT (DEPTNO = 10 AND COMM IS NULL);

SELECT *
  FROM EMP
 WHERE DEPTNO = 10 AND COMM IS NULL;

SELECT *
  FROM EMP
 WHERE DEPTNO = 10 OR COMM IS NULL;

SELECT *
  FROM EMP
 WHERE DEPTNO <> 10 OR COMM IS NOT NULL;

SELECT *
  FROM EMP
 WHERE DEPTNO <> 10 AND COMM IS NOT NULL;
