DROP TABLE T1 PURGE;

CREATE TABLE T1 (C1 NUMBER);

INSERT INTO T1 (C1) VALUES ( 100);
INSERT INTO T1 (C1) VALUES (NULL);
INSERT INTO T1 (C1) VALUES (NULL);
INSERT INTO T1 (C1) VALUES ( 200);
INSERT INTO T1 (C1) VALUES ( 300);

COMMIT;

SELECT AVG (C1) AS R1 FROM T1;

SELECT AVG (C1) AS R1 FROM T1 WHERE C1 IS NOT NULL;

SELECT AVG (NVL (C1, 0)) AS R1 FROM T1;

SELECT NVL (AVG (C1), 0) AS R1 FROM T1;
