SELECT *
  FROM DEPT
 WHERE DEPTNO IN (SELECT DEPTNO FROM EMP);

SELECT A.*
  FROM DEPT A
 WHERE EXISTS (SELECT 1 FROM EMP X WHERE X.DEPTNO = A.DEPTNO);

SELECT B.*
  FROM (SELECT DISTINCT DEPTNO FROM EMP) A
     , DEPT B
 WHERE B.DEPTNO = A.DEPTNO;

SELECT DISTINCT
       A.*
  FROM DEPT A, EMP B
 WHERE B.DEPTNO(+) = A.DEPTNO;
