DROP TABLE T1 PURGE;
DROP TABLE T2 PURGE;

CREATE TABLE T1 (C1 NUMBER);
CREATE TABLE T2 (C1 NUMBER);

INSERT INTO T1 VALUES (1);
INSERT INTO T1 VALUES (2);
INSERT INTO T1 VALUES (3);
INSERT INTO T1 VALUES (4);

INSERT INTO T2 VALUES (1);
INSERT INTO T2 VALUES (2);
INSERT INTO T2 VALUES (2);

COMMIT;

SELECT COUNT (*) AS CNT
  FROM T1 A
 WHERE EXISTS (SELECT COUNT (*) FROM T2 X WHERE X.C1 = A.C1);
