SELECT A.*
  FROM (SELECT TOP (5)
               A.*
          FROM (SELECT TOP (10)
                       EMPNO, ENAME, SAL
                  FROM EMP
                  ORDER BY SAL DESC) A
        ORDER BY SAL) A
ORDER BY SAL DESC;

SELECT EMPNO, ENAME, SAL
  FROM EMP
 ORDER BY SAL DESC OFFSET 5 ROWS FETCH NEXT 5 ROWS ONLY;

SELECT A.*
  FROM (SELECT EMPNO, ENAME, SAL, ROW_NUMBER () OVER (ORDER BY A.SAL DESC) AS RN
          FROM EMP A) A
 WHERE A.RN BETWEEN 6 AND 10;
