SELECT EMPNO, ENAME, SAL
  FROM EMP
 ORDER BY SAL DESC FETCH FIRST 4 ROWS WITH TIES;

SELECT *
  FROM (SELECT EMPNO, ENAME, SAL
             , RANK () OVER (ORDER BY SAL DESC) AS RN
          FROM EMP)
 WHERE RN <= 4;
