DROP TABLE T1 PURGE;
DROP TABLE T2 PURGE;

CREATE TABLE T1 (C1 NUMBER, C2 NUMBER);
CREATE TABLE T2 (C1 NUMBER, C2 NUMBER);

INSERT INTO T1 VALUES (1, 1);
INSERT INTO T1 VALUES (2, 1);
INSERT INTO T1 VALUES (3, 1);
INSERT INTO T2 VALUES (1, 1);

COMMIT;

DELETE
  FROM T1 A
 WHERE EXISTS (SELECT 1 FROM T2 X WHERE X.C1 = C1);
