DROP TABLE T1 PURGE;
DROP TABLE T2 PURGE;

CREATE TABLE T1 (C1 NUMBER, C2 NUMBER);
CREATE TABLE T2 (C1 NUMBER, C2 NUMBER);

INSERT INTO T1 VALUES (1, 1);
INSERT INTO T1 VALUES (2, 1);
INSERT INTO T1 VALUES (3, 1);
INSERT INTO T2 VALUES (3, 3);
INSERT INTO T2 VALUES (4, 4);
INSERT INTO T2 VALUES (5, 5);

COMMIT;

MERGE
 INTO T1 T
USING T2 S
   ON (T.C1 = S.C1)
 WHEN MATCHED THEN
      UPDATE SET T.C2 = S.C2 WHERE S.C2 > 2
      DELETE WHERE T.C2 < 2
 WHEN NOT MATCHED THEN
      INSERT (T.C1, T.C2) VALUES (S.C1, S.C2) WHERE S.C2 > 4;

SELECT * FROM T1;

MERGE
 INTO T1 T
USING T2 S
   ON (T.C1 = S.C1)
 WHEN MATCHED THEN
      UPDATE SET T.C2 = S.C2 - 2 WHERE S.C2 > 2
      DELETE WHERE T.C2 < 2
 WHEN NOT MATCHED THEN
      INSERT (T.C1, T.C2) VALUES (S.C1, S.C2) WHERE S.C2 > 4;
