DROP TABLE T1 PURGE;

CREATE TABLE T1 AS SELECT CAST (1 AS NUMBER(1)) AS C1 FROM XMLTABLE ('1 to 1000000');

ALTER TABLE T1 ADD C2 NUMBER;
ALTER TABLE T1 MODIFY C1 NUMBER(10);
ALTER TABLE T1 DROP COLUMN C1;
ALTER TABLE T1 RENAME COLUMN C2 TO C1;

ALTER TABLE T1 ADD C3 NUMBER DEFAULT 1 NOT NULL;
ALTER TABLE T1 ADD C4 NUMBER DEFAULT 1;
