WITH W1 (EMPNO, ENAME, MGR) AS (
SELECT EMPNO, ENAME, MGR
  FROM EMP
 WHERE ENAME = 'JONES'
UNION ALL
SELECT C.EMPNO, C.ENAME, C.MGR
  FROM W1 P, EMP C
 WHERE C.EMPNO = P.MGR)
SELECT EMPNO, ENAME, MGR
  FROM W1;
