SELECT JOB
     , SUM (CASE DEPTNO WHEN 10 THEN SAL END) AS D10_SAL
     , SUM (CASE DEPTNO WHEN 20 THEN SAL END) AS D20_SAL
  FROM EMP
 WHERE DEPTNO IN (10, 20)
 GROUP BY JOB
 ORDER BY JOB;

SELECT JOB
     , DEPTNO
     , CASE DEPTNO WHEN 10 THEN SAL END AS D10_SAL
     , CASE DEPTNO WHEN 20 THEN SAL END AS D20_SAL
  FROM EMP
 WHERE DEPTNO IN (10, 20)
 ORDER BY JOB;
