DROP TABLE T1 PURGE;

CREATE TABLE T1 (C1 NUMBER PRIMARY KEY, C2 VARCHAR2(2));

INSERT INTO T1 (C1, C2) VALUES (1, 'A');
INSERT INTO T1 (C1, C2) VALUES (2, 'B');
INSERT INTO T1 (C1, C2) VALUES (3, NULL);
INSERT INTO T1 (C1, C2) VALUES (4, 'A');
INSERT INTO T1 (C1, C2) VALUES (5, 'B');

COMMIT;

SELECT COUNT (C1) + COUNT (DISTINCT C1) AS R1 FROM T1;
