DROP TABLE T1 PURGE;

CREATE TABLE T1 (C1 NUMBER, C2 VARCHAR2(4), C3 VARCHAR2(2));

INSERT INTO T1 (C1, C2, C3) VALUES (1, 'ABCD', 'AB');
INSERT INTO T1 (C1, C2, C3) VALUES (2, 'EFGH', 'EF');

COMMIT;

SELECT * FROM T1;

SELECT C1, C2 FROM T1;

SELECT C1 || C2, C3 AS R1 FROM T1;

SELECT * FROM (SELECT C1, C2 FROM T1);
