DROP TABLE T1 PURGE;

CREATE TABLE T1 (C1 NUMBER, C2 VARCHAR2(3));

INSERT INTO T1 (C1, C2) VALUES (1, 'ABC');
INSERT INTO T1 (C1, C2) VALUES (2, NULL);
INSERT INTO T1 (C1, C2) VALUES (3, 'CBA');

COMMIT;

SELECT CASE
           WHEN C1 = 3 THEN 'A'
           WHEN SUBSTR (C2, 2, 1) = 'B' THEN 'B'
           ELSE 'C'
       END AS R1
  FROM T1;
