DROP TABLE T1 PURGE;

CREATE TABLE T1 (C1 NUMBER, C2 VARCHAR2(1));

INSERT INTO T1 (C1, C2) VALUES (1, 'A');
INSERT INTO T1 (C1, C2) VALUES (2, 'B');
INSERT INTO T1 (C1, C2) VALUES (3, 'C');
INSERT INTO T1 (C1, C2) VALUES (4, 'D');

COMMIT;

SELECT *
  FROM T1
 WHERE (C1 = 1 AND C2 = 'A')
    OR (C1 = 3 AND C2 = 'C');

SELECT *
  FROM T1
 WHERE (C1, C2) IN ( (1, 'A'), (3, 'C') );
