DROP TABLE T1 PURGE;

CREATE TABLE T1 (C1 NUMBER PRIMARY KEY, C2 VARCHAR2(2), C3 VARCHAR2(4) NOT NULL);

INSERT INTO T1 (C1, C2, C3) VALUES (1, 'AB', 'AAAA');
INSERT INTO T1 (C1, C2, C3) VALUES (2, NULL, 'ABCD');
INSERT INTO T1 (C1, C2, C3) VALUES (3, 'CD', 'BBBB');
INSERT INTO T1 (C1, C2, C3) VALUES (4, NULL, 'BBBB');

COMMIT;

SELECT COUNT (*)  AS R1 FROM T1;

SELECT COUNT (C1) AS R1 FROM T1;

SELECT COUNT (C2) AS R1 FROM T1;

SELECT COUNT (C3) AS R1 FROM T1;
