DROP TABLE T1 PURGE;

CREATE TABLE T1 (C1 NUMBER, C2 VARCHAR(1));

INSERT INTO T1 (C1, C2) VALUES (1, 'A');
INSERT INTO T1 (C1, C2) VALUES (2, 'A');
INSERT INTO T1 (C1, C2) VALUES (3, 'B');
INSERT INTO T1 (C1, C2) VALUES (4, 'C');

COMMIT;

SELECT SUM (DECODE (C2, 'A', C1, 'B', 1)) AS R1 FROM T1;
