DROP TABLE T1 PURGE;

CREATE TABLE T1 (C1 VARCHAR2(3), C2 VARCHAR2(3));

INSERT INTO T1 (C1, C2) VALUES ('A'  , 'XYZ');
INSERT INTO T1 (C1, C2) VALUES ('ABC', 'X');
INSERT INTO T1 (C1, C2) VALUES ('CBA', 'WX');
INSERT INTO T1 (C1, C2) VALUES ('C'  , 'V');

COMMIT;

SELECT C1, C2
  FROM T1
 ORDER BY SUBSTR (C1, 1, 1), LENGTH (C2);
