DROP TABLE T1 PURGE;
DROP TABLE T2 PURGE;

CREATE TABLE T1 (C1 NUMBER, C2 VARCHAR2(1));
CREATE TABLE T2 (C1 NUMBER, C2 VARCHAR2(1));

INSERT INTO T1 (C1, C2) VALUES (1, 'A');
INSERT INTO T1 (C1, C2) VALUES (2, 'B');
INSERT INTO T1 (C1, C2) VALUES (3, 'C');
INSERT INTO T1 (C1, C2) VALUES (4, 'D');

INSERT INTO T2 (C1, C2) VALUES (1, 'A');
INSERT INTO T2 (C1, C2) VALUES (2, 'B');
INSERT INTO T2 (C1, C2) VALUES (3, 'B');
INSERT INTO T2 (C1, C2) VALUES (3, 'C');
INSERT INTO T2 (C1, C2) VALUES (5, 'C');

COMMIT;

SELECT COUNT (A.C1) AS CNT_A
     , COUNT (B.C1) AS CNT_B
  FROM T1 A RIGHT OUTER JOIN T2 B
    ON B.C1 = A.C1
   AND B.C1 >= 3;
