SELECT *
  FROM EMP
 WHERE SAL > (SELECT SAL FROM EMP WHERE EMPNO = 7369);

SELECT *
  FROM EMP
 WHERE SAL > (SELECT AVG (SAL) FROM EMP);

SELECT *
  FROM EMP
 WHERE SAL > (SELECT SAL
                FROM (SELECT SAL FROM EMP ORDER BY HIREDATE DESC)
               WHERE ROWNUM = 1);

SELECT *
  FROM EMP
 WHERE SAL > (SELECT SAL
                FROM (SELECT SAL, RANK () OVER (ORDER BY SAL DESC) AS RK
                        FROM EMP
                       WHERE SAL < 1300)
               WHERE RK = 1);
