SELECT EMPNO, ENAME, SAL, DEPTNO
  FROM EMP
 WHERE (DEPTNO, SAL) IN (SELECT DEPTNO, MAX (SAL)
                           FROM EMP
                          GROUP BY DEPTNO);

SELECT EMPNO, ENAME, SAL, DEPTNO
  FROM (SELECT A.*
             , RANK () OVER (PARTITION BY DEPTNO ORDER BY SAL DESC) AS RK
          FROM EMP A)
 WHERE RK = 1;

SELECT EMPNO, ENAME, SAL, DEPTNO
  FROM (SELECT A.*
             , DENSE_RANK () OVER (PARTITION BY DEPTNO ORDER BY SAL DESC) AS RK
          FROM EMP A)
 WHERE RK = 1;
