SELECT A.DEPTNO, A.DNAME
     , (SELECT MAX (X.SAL ) FROM EMP X WHERE X.DEPTNO = A.DEPTNO) AS SAL
     , (SELECT MAX (X.COMM) FROM EMP X WHERE X.DEPTNO = A.DEPTNO) AS COMM
  FROM DEPT A;

SELECT A.DEPTNO, A.DNAME, B.SAL, B.COMM
  FROM DEPT A
     , (SELECT DEPTNO, MAX (SAL) AS SAL, MAX (COMM) AS COMM
          FROM EMP
         GROUP BY DEPTNO) B
 WHERE B.DEPTNO(+) = A.DEPTNO;
