DROP TABLE T1 PURGE;
DROP TABLE T2 PURGE;
DROP TABLE T3 PURGE;

CREATE TABLE T1 (C1 NUMBER);
CREATE TABLE T2 (C1 NUMBER);
CREATE TABLE T3 (C1 NUMBER);

INSERT INTO T1 VALUES (1);
INSERT INTO T1 VALUES (2);
INSERT INTO T1 VALUES (3);

INSERT INTO T2 VALUES (1);
INSERT INTO T2 VALUES (4);

INSERT INTO T3 VALUES (2);
INSERT INTO T3 VALUES (3);

COMMIT;

SELECT COUNT (*) AS CNT
  FROM (SELECT C1 FROM T1
        UNION
        SELECT C1 FROM T2
        MINUS
        SELECT C1 FROM T3);
