DROP TABLE T1 PURGE;
DROP TABLE T2 PURGE;

CREATE TABLE T1 (C1 VARCHAR2(1), C2 NUMBER);
CREATE TABLE T2 (C1 VARCHAR2(1), C3 NUMBER);

INSERT INTO T1 VALUES ('A', 1);
INSERT INTO T1 VALUES ('A', 1);
INSERT INTO T1 VALUES ('B', 1);

INSERT INTO T2 VALUES ('B', 1);
INSERT INTO T2 VALUES ('C', 1);
INSERT INTO T2 VALUES ('C', 1);

COMMIT;

SELECT   C1, SUM (C2) AS C2, SUM (C3) AS C3
    FROM (SELECT C1, C2, NULL AS C3 FROM T1
          UNION ALL
          SELECT C1, NULL AS C2, C3 FROM T2)
GROUP BY C1
ORDER BY C1;
