DROP TABLE T1 PURGE;
DROP TABLE T2 PURGE;

CREATE TABLE T1 (C1 NUMBER);
CREATE TABLE T2 (C1 NUMBER);

INSERT INTO T1 VALUES (1);
INSERT INTO T1 VALUES (1);
INSERT INTO T1 VALUES (2);

INSERT INTO T2 VALUES (2);
INSERT INTO T2 VALUES (3);

COMMIT;

SELECT C1 FROM T1
MINUS
SELECT C1 FROM T2;

SELECT DISTINCT
       A.C1
  FROM T1 A
 WHERE NOT EXISTS (SELECT 1
                     FROM T2 X
                    WHERE X.C1 = A.C1);
