SELECT EMPNO, ENAME, SAL, ROWNUM AS RN
  FROM EMP
 WHERE DEPTNO IN (20, 30)
   AND ROWNUM <= 3
 ORDER BY SAL DESC;

SELECT EMPNO, ENAME, SAL, ROWNUM AS RN
  FROM EMP
 WHERE DEPTNO IN (20, 30)
   AND ROWNUM <= 3;

SELECT A.*, ROWNUM AS RN
  FROM (SELECT EMPNO, ENAME, SAL
          FROM EMP
         WHERE DEPTNO IN (20, 30)
         ORDER BY SAL DESC) A
 WHERE ROWNUM <= 3;
