SELECT *
  FROM (SELECT EMPNO, ENAME, SAL
         FROM EMP
        ORDER BY SAL DESC)
 WHERE ROWNUM <= 3;

SELECT TOP (3)
       EMPNO, ENAME, SAL
  FROM EMP
 ORDER BY SAL DESC;

SELECT EMPNO, ENAME, SAL
  FROM EMP
 ORDER BY SAL DESC OFFSET 3 ROWS;

SELECT EMPNO, ENAME, SAL
  FROM EMP
 ORDER BY SAL DESC FETCH FIRST 3 ROWS ONLY;

SELECT EMPNO, ENAME, SAL
  FROM (SELECT EMPNO, ENAME, SAL
             , ROW_NUMBER () OVER (ORDER BY SAL DESC) AS RN
          FROM EMP)
 WHERE RN <= 3;
