WITH W1 (EMPNO, ENAME, MGR, LV) AS (
SELECT EMPNO, ENAME, MGR, 1 AS LV
  FROM EMP
 WHERE ENAME = 'JONES'
UNION ALL
SELECT C.EMPNO, C.ENAME, C.MGR, P.LV + 1 AS LV
  FROM W1 P, EMP C
 WHERE C.MGR = P.EMPNO)
SELECT EMPNO, ENAME, MGR, LV
  FROM W1;
