DROP TABLE T1 PURGE;
DROP TABLE T2 PURGE;

CREATE TABLE T1 (C1 NUMBER, C2 NUMBER);
CREATE TABLE T2 (C1 NUMBER, C2 NUMBER);

INSERT INTO T1 VALUES (1, 1);
INSERT INTO T1 VALUES (2, 1);
INSERT INTO T1 VALUES (3, 1);
INSERT INTO T2 VALUES (1, 1);
INSERT INTO T2 VALUES (2, NULL);

COMMIT;

DELETE FROM T1 WHERE C1 NOT IN (SELECT C2 FROM T2);

SELECT COUNT (*) AS CNT FROM T1;
