DROP TABLE T1 PURGE;

CREATE TABLE T1 (C1 NUMBER);

INSERT INTO T1 VALUES (1);
INSERT INTO T1 VALUES (2);
ALTER TABLE T1 ADD C2 NUMBER;
INSERT INTO T1 VALUES (3, 3);
ROLLBACK;

SELECT COUNT(*) FROM T1;