DROP TABLE T1 PURGE;

CREATE TABLE T1 (C1 NUMBER(2));

INSERT INTO T1 VALUES (1);

COMMIT;

ALTER TABLE T1 MODIFY C1 NUMBER(1);
ALTER TABLE T1 MODIFY C1 NUMBER(3);
ALTER TABLE T1 MODIFY C1 NOT NULL;
ALTER TABLE T1 MODIFY C1 NULL;
