DROP TABLE T1 PURGE;
DROP TABLE T2 PURGE;

CREATE TABLE T1 (C1 NUMBER, CONSTRAINT T1_PK PRIMARY KEY (C1));
CREATE TABLE T2 (C1 NUMBER, CONSTRAINT T1_FK FOREIGN KEY (C1) REFERENCES T1 (C1));

ALTER TABLE T1 RENAME COLUMN C1 TO C2;
ALTER TABLE T2 RENAME COLUMN C1 TO C2;
DROP TABLE T1;
DROP TABLE T2;

DROP TABLE T1 CASCADE CONSTRAINTS;
