DROP TABLE T1 PURGE;
DROP TABLE T2 PURGE;

CREATE TABLE T1 (C1 NUMBER);
CREATE TABLE T2 (C1 NUMBER);

ALTER TABLE T1 ADD CONSTRAINT T1_PK PRIMARY KEY (C1);
ALTER TABLE T2 ADD CONSTRAINT T2_U1 UNIQUE (C1);

INSERT INTO T1 VALUES (1);
INSERT INTO T1 VALUES (1);
INSERT INTO T1 VALUES (NULL);
INSERT INTO T1 VALUES (NULL);

SELECT COUNT (*) AS CNT FROM T1;

INSERT INTO T2 VALUES (1);
INSERT INTO T2 VALUES (1);
INSERT INTO T2 VALUES (NULL);
INSERT INTO T2 VALUES (NULL);

SELECT COUNT (*) AS CNT FROM T2;
