-- SYS
DROP USER U1 CASCADE;
DROP USER U2 CASCADE;

CREATE USER U1 IDENTIFIED BY U1;
CREATE USER U2 IDENTIFIED BY U2;

GRANT CREATE SESSION TO U1, U2;

-- U1
CREATE TABLE U2.T1 (C1 NUMBER);

-- SYS
GRANT CREATE ANY TABLE TO U1;

-- U1
CREATE TABLE U2.T1 (C1 NUMBER);
