-- SYS
DROP USER U2 CASCADE;
CREATE USER U2 IDENTIFIED BY U2;
GRANT CREATE SESSION TO U2;

-- U2
CREATE TABLE T1 (C1 NUMBER);

INSERT INTO T1 VALUES (1);

-- SYS
GRANT UNLIMITED TABLESPACE TO U2;

-- U2
INSERT INTO T1 VALUES (1);
