-- SYS
DROP USER U1 CASCADE;
DROP USER U2 CASCADE;

CREATE USER U1 IDENTIFIED BY U1;
CREATE USER U2 IDENTIFIED BY U2;

GRANT CREATE SESSION TO U1, U2;

-- U2
CREATE TABLE T1 (C1 NUMBER);

GRANT ALTER      ON T1 TO U1;
GRANT EXECUTE    ON T1 TO U1;
GRANT INDEX      ON T1 TO U1;
GRANT REFERENCES ON T1 TO U1;
