DROP TABLE T1 PURGE;
DROP TABLE T2 PURGE;

CREATE TABLE T1 (C1 NUMBER, C2 NUMBER, CONSTRAINT T1_PK PRIMARY KEY (C1));
CREATE TABLE T2 (C1 NUMBER, C2 NUMBER, CONSTRAINT T2_PK PRIMARY KEY (C1));

INSERT INTO T1 VALUES (1, 1);
INSERT INTO T2 VALUES (1, 1);
INSERT INTO T2 VALUES (2, 1);
INSERT INTO T2 VALUES (3, 1);
INSERT INTO T2 VALUES (4, 1);

COMMIT;

INSERT
  INTO T1
SELECT A.C1, A.C2
  FROM T2 A;

INSERT
  INTO T1
SELECT A.C1, A.C2
  FROM T2 A
 WHERE NOT EXISTS (SELECT 1
                     FROM T1 X
                    WHERE X.C1 = A.C1);

SELECT COUNT (*) AS CNT FROM T1;
