DROP TABLE T1 PURGE;
DROP TABLE T2 PURGE;

CREATE TABLE T1 (C1 NUMBER, C2 NUMBER);
CREATE TABLE T2 (C1 NUMBER, C2 NUMBER);

INSERT INTO T1 VALUES (1, 1);
INSERT INTO T2 VALUES (1, 1);
INSERT INTO T2 VALUES (1, 2);
INSERT INTO T2 VALUES (1, 3);

COMMIT;

UPDATE (SELECT A.C2 AS AC2, B.C2 AS BC2
          FROM T1 A
             , (SELECT C1, MAX (C2) AS C2 FROM T2 GROUP BY C1) B
         WHERE B.C1 = A.C1)
   SET AC2 = BC2;

SELECT * FROM T1;
