DROP TABLE T1 PURGE;
DROP TABLE T2 PURGE;

CREATE TABLE T1 (C1 NUMBER, C2 NUMBER);
CREATE TABLE T2 (C1 NUMBER, C2 NUMBER);

INSERT INTO T1 VALUES (1, 1);
INSERT INTO T2 VALUES (1, 2);
INSERT INTO T2 VALUES (1, 3);
INSERT INTO T2 VALUES (1, 4);

COMMIT;

MERGE
 INTO T1 T
USING T2 S
   ON (T.C1 = S.C1)
 WHEN MATCHED THEN
      UPDATE SET T.C2 = S.C2;

SELECT COUNT (*) AS CNT FROM T1;
