DROP TABLE T1 PURGE;
DROP TABLE T2 PURGE;

CREATE TABLE T1 (C1 NUMBER(1));
CREATE TABLE T2 (C1 NUMBER);

INSERT INTO T2 VALUES ( 8);
INSERT INTO T2 VALUES ( 9);
INSERT INTO T2 VALUES (10);

COMMIT;

INSERT INTO T1 VALUES (7);
INSERT INTO T1 SELECT * FROM T2;
DELETE FROM T1 WHERE C1 = 9;

SELECT MAX (C1) AS C1 FROM T1;
