DROP TABLE T1 PURGE;
DROP TABLE T2 PURGE;
CREATE TABLE T1 AS SELECT ROWNUM AS C1 FROM XMLTABLE ('1 to 100');
CREATE TABLE T2 AS SELECT ROWNUM AS C1 FROM XMLTABLE ('1 to 100');

DELETE FROM T1;
ROLLBACK;
SELECT COUNT (*) AS CNT FROM T1;

TRUNCATE TABLE T2;
ROLLBACK;
SELECT COUNT (*) AS CNT FROM T2;
