DROP TABLE T1 PURGE;
CREATE TABLE T1 (C1 CHAR(2), C2 VARCHAR2(2));

INSERT INTO T1 VALUES ('A' , 'A' );
INSERT INTO T1 VALUES ('B' , 'B ');
INSERT INTO T1 VALUES ('C ', 'C' );
INSERT INTO T1 VALUES ('D ', 'D ');

COMMIT;

SELECT * FROM T1 WHERE C1 = C2;
