-- 통과함 무지성 조인방식
SELECT
      A.REST_ID
    , A.REST_NAME
    , A.FOOD_TYPE
    , A.FAVORITES
    , A.ADDRESS
    , ROUND(AVG(B.REVIEW_SCORE), 2) SCORE
FROM REST_INFO  A, REST_REVIEW  B
WHERE A.REST_ID = B.REST_ID
AND A.ADDRESS LIKE '서울%'
GROUP BY
      A.REST_ID
    , A.REST_NAME
    , A.FOOD_TYPE
    , A.FAVORITES
    , A.ADDRESS
ORDER BY 6 DESC, 4 DESC

-- 통과함 1: N 집합에서 N집합을 먼저 REST_ID 그룹핑을 진행하여 1집합으로 축소시킨다.
-- 단, 조인에 성공하는 
SELECT 
      A.REST_ID
    , A.REST_NAME
    , A.FOOD_TYPE
    , A.FAVORITES
    , A.ADDRESS
    , NVL(B.SCORE, 0) SCORE -- 리뷰를 받아본적 없는 식당의 경우 null 이 나오는데... ==> NVL 혹은 
FROM REST_INFO  A, 
    (SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) SCORE FROM REST_REVIEW GROUP BY REST_ID)  B
WHERE A.REST_ID = B.REST_ID(+)
AND A.ADDRESS LIKE '서울%'
ORDER BY 6 DESC, 4 DESC


-- 통과못함
SELECT 
      A.REST_ID
    , A.REST_NAME
    , A.FOOD_TYPE
    , A.FAVORITES
    , A.ADDRESS
    , COALESCE(
        (SELECT ROUND(AVG(B.REVIEW_SCORE), 2) FROM REST_REVIEW B WHERE B.REST_ID = A.REST_ID GROUP BY B.REST_ID)
        ,0) SCORE
FROM REST_INFO A
WHERE A.ADDRESS LIKE '서울%'
ORDER BY 6 DESC, 4 DESC